### ISSUE TITLE
Preprint can't be accessed 

### ISSUE THREAD

**Issue by nmandic78** [traulab/DIYNAFLUOR#21]
https://www.biorxiv.org/content/10.1101/2024.12.16.626200v1.full.pdf
![image](https://github.com/user-attachments/assets/9bd65827-3ae5-4ef9-b873-c56b9edcc12a)

Also tried in Safari on mobile phone and it is same 38 bytes

**Comment by willanderson01** [comment]
This appears to be an issue with biorxiv. If the Preprint is still unavailable later today, I will make it available here.

**Comment by willanderson01** [comment]
Looks like its back up now. Let me know if it goes down again. :)
